#!/usr/bin/env bash
# Redémarrage gracieux de Gunicorn

# Trouver le PID de Gunicorn
pid=$(pgrep gunicorn)

# Si le PID est trouvé, redémarrez Gunicorn de manière gracieuse
if [ -n "$pid" ]; then
    echo "Redémarrage gracieux de Gunicorn..."
    kill -HUP "$pid"
    echo "Gunicorn redémarré avec succès."
else
    echo "Aucun processus Gunicorn en cours d'exécution."
fi